### ISSUE TITLE
[Bug] Alpha masked textures doesn't work with BDPT integrator

### ISSUE THREAD

**Issue by odil24** [YafaRay/Blender-Exporter#38]
I'm just test this file using BDPT and the transparency of the textures didnt works with it:
http://www.yafaray.org/phpBB3/download/file.php?id=7413

**Comment by DavidBluecame** [comment]
Hello,

Thank you for the bug report. I can replicate the problem and will look into it. However, keep in mind that the Bidirectional integrator is unstable and does not work as well as the other integrators.

Thanks!

**Comment by odil24** [comment]
Any news here?

**Comment by DavidBluecame** [comment]
Hi,

BDPT is really unstable and its current implementation questionable in my opinion... I'll try to do something about this but not easy (to say the least)

**Comment by DavidBluecame** [comment]
Hello, I've added some code to fix this. This will be available in the next release v3.5.0, so I'm closing this.

This is how it looks like now:
![cutout01 - 001](https://user-images.githubusercontent.com/3886025/87148912-939fa500-c2af-11ea-86d3-64036f1504b9.png)
