### ISSUE TITLE
[Bug] Black dots when using BDPT (Bidirectional Pathtracing)

### ISSUE THREAD

**Issue by odil24** [YafaRay/Blender-Exporter#39]
When using Oren-Nayer reflectance model and value not 0 for it, so blackdots appeared. Moreover, example:
1. Create material;
2. Oren-Nayer value is Default (0.1 in this case);
3. Goto Texture>New texture>Set texture>Tick Bump checkbox (Normal map).
4. Render>Blackdots appearing.

Note: Didn't pasted .blend file, because It shawn always in any situation when Oren-Nayer set to default and Bump>Normal map options Enabled, BUT ALSO if Oren-Nayer set to 0 value, so blackdots are disappeared.

**Comment by DavidBluecame** [comment]
Hi,

I could not replicate this problem, please can you provide a blend file and a screenshot showing the results you are getting?

Thanks!

**Comment by DavidBluecame** [comment]
Hello,

Please will you provide an example blend file? Thanks.
