### ISSUE TITLE
[Bug] Camera tile shift is not works on SPPM integrator

### ISSUE THREAD

**Issue by odil24** [YafaRay/Blender-Exporter#41]
This is known issue which is found here: https://github.com/YafaRay/Blender-Exporter/issues/40
And now need to be revision.

**Comment by odil24** [comment]
This settings are must not to be changed:
[IMG]https://cdn-32.anonfiles.com/1874k959o3/4d7e7182-1591471748/%D0%91%D0%B5%D0%B7%D1%8B%D0%BC%D1%8F%D0%BD%D0%BD%D1%8B%D0%B9.jpg[/IMG]

**Comment by DavidBluecame** [comment]
Yes, I agree I should try to get this fixed. Thanks.

**Comment by DavidBluecame** [comment]
Hello, I've added some code to fix this. This should be fixed in the next release v3.5.0
